// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpP8hsEL9iRf-tQtgGEwaM4J9pnGAEPK4',
    appId: '1:700218829957:web:0e8727b892378c242e8dec',
    messagingSenderId: '700218829957',
    projectId: 'gru-watch',
    authDomain: 'gru-watch.firebaseapp.com',
    databaseURL: 'https://gru-watch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gru-watch.firebasestorage.app',
    measurementId: 'G-9218YNNWTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADTe2ArYxy8guB7_2AmbhoqWgg1e8T3Dw',
    appId: '1:700218829957:android:30eff19dba630d4c2e8dec',
    messagingSenderId: '700218829957',
    projectId: 'gru-watch',
    databaseURL: 'https://gru-watch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gru-watch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYV5oHSl1LjskdwLyoyhD5Z6i8ii5_hgQ',
    appId: '1:700218829957:ios:93cb1f5e9a095fb02e8dec',
    messagingSenderId: '700218829957',
    projectId: 'gru-watch',
    databaseURL: 'https://gru-watch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gru-watch.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYV5oHSl1LjskdwLyoyhD5Z6i8ii5_hgQ',
    appId: '1:700218829957:ios:93cb1f5e9a095fb02e8dec',
    messagingSenderId: '700218829957',
    projectId: 'gru-watch',
    databaseURL: 'https://gru-watch-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gru-watch.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
